### ISSUE TITLE
Easier build, build instructions

### ISSUE THREAD

**Issue by biafra23** [OpenJavaCard/openjavacard-tools#1]
When I try to build the project with `ant` I get the following error:

`BUILD FAILED
/home/fnord/openjavacard-tools/build.xml:43: srcdir "/home/fnord/openjavacard-tools/dep/commons-codec/src/main/java" does not exist!`

What do I need to do to build the project?

**Comment by promovicz** [comment]
The ant build requires pulling the dependencies as submodules:

$ git submodule update --init

This is so one can easily build the tools in a closed environment.

I will soon provide a Maven build that will make this unnecessary.

**Comment by biafra23** [comment]
Would you consider accepting a PR containing a build.gradle file and gradle wrapper configuration?

**Comment by promovicz** [comment]
Yes, thank you very much.

While I am not a fan of Gradle it can bridge the gap.
